version: "3.9"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion:2.1.0
    container_name: nginx-proxy-acme
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  default:
    external: true
    name: zkbob
