version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli:v6.12.0
    command: >
      --deterministic
      --gasLimit 20000000
      --allowUnlimitedContractSize
      --networkId 1337
      --chainId 1337
    ports:
      - 8545:8545
  contracts:
    image: lok52/zp-contracts:latest
    depends_on:
      - ganache
  redis:
    container_name: redis
    command: [redis-server, --port, '6379', --appendonly, 'yes']
    image: redis:6.2.6
    ports:
      - 6379:6379
  relayer:
    image: lok52/zp-relayer:latest
    container_name: relayer
    volumes:
      - $PARAMS_PATH:/app/zp-relayer/params/
    ports:
      - 8000:8000
    env_file: ./relayer.env
