name: zkbob-relayer

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Evaluate relayer tag
        id: tag
        uses: EndBug/version-check@v1
        with:
          file-name: ./zp-relayer/package.json
    outputs:
      version: ${{ steps.tag.outputs.version }}
      changed: ${{ steps.tag.outputs.changed }}
  build-and-push:
    runs-on: ubuntu-latest
    needs: check-version
    if: ${{ needs.check-version.outputs.changed }} == 'true'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docker/Dockerfile.relayer
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/zp-relayer:${{ needs.check-version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/zp-relayer:latest
          cache-from: type=gha
          cache-to: type=gha