name: zkbob-relayer

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ghcr.io/akolotov/zkbob-relayer

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Evaluate relayer tag
        id: tag
        uses: EndBug/version-check@v1
        with:
          file-name: ./zp-relayer/package.json
    outputs:
      version: ${{ steps.tag.outputs.version }}
      changed: ${{ steps.tag.outputs.changed }}
  build-and-push:
    runs-on: ubuntu-latest
    needs: check-version
    if: needs.check-version.outputs.changed == 'true'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./docker/Dockerfile.relayer
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/zp-relayer:${{ needs.check-version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/zp-relayer:latest
          cache-from: type=gha
          cache-to: type=gha
